name       : scribus
version    : 1.4.6
release    : 4
source     :
    - http://netix.dl.sourceforge.net/project/scribus/scribus/1.4.6/scribus-1.4.6.tar.xz : 21e336500d9edc9c90ccf73087e5ef3df59ec3e4a3cbfec15367bcd8d078a19a
license    : GPL-2.0
summary    : Desktop publishing software
description: |
    Desktop publishing software
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gl)
    - pkgconfig(lcms2)
    - pkgconfig(libtiff-4)
    - pkgconfig(python-2.7)
    - pkgconfig(QtCore)
    - cups-devel
    - ghostscript-devel
    - hyphen-devel
    - libboost-devel
    - libjpeg-turbo-devel
    - podofo-devel
setup      : |
    ln -s /usr/bin/rcc-qt4 /usr/bin/rcc
    %cmake .
build      : |
    %make
install    : |
    %make_install
    install -Dm644 scribus.desktop $installdir/usr/share/applications/scribus.desktop
    install -Dm644 resources/icons/AppIcon.png $installdir/usr/share/icons/hicolor/32x32/apps/scribus.png
