name       : scribus
version    : 1.5.7
release    : 27
source     :
    - https://sourceforge.net/projects/scribus/files/scribus-devel/1.5.7/scribus-1.5.7.tar.gz/download : ff9678e18d9eebf4e381d18eb40c5477b6fa28112481733db647d39a8d58aac7
license    :
    - LGPL-2.0-or-later
    - BSD-3-Clause
    - MIT
component  : office
summary    : Desktop publishing software
description: |
    Scribus is an Open Source program that brings professional page layout with a combination of press-ready output and new approaches to page design. Underneath a modern and user-friendly interface, Scribus supports professional publishing features, such as color separations, CMYK and spot colors, ICC color management, and versatile PDF creation.
patterns   :
    - docs :
        - /usr/share/doc
builddeps  :
    - pkgconfig(GraphicsMagick)
    - pkgconfig(hunspell)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(libpodofo-0)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler)
    - pkgconfig(python3)
    - pkgconfig(Qt5UiTools)
    - cups-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DWANT_NORPATH=1 -DWANT_GRAPHICSMAGICK=1
build      : |
    %ninja_build
install    : |
    %ninja_install
