name       : scribus
version    : 1.5.8
release    : 39
source     :
    - https://sourceforge.net/projects/scribus/files/scribus-devel/1.5.8/scribus-1.5.8.tar.gz/download : 1b95bc12f04fa1d081d2535df78a6a9e5b637dc9409e59828af0e8905e4dc191
license    :
    - LGPL-2.0-or-later
    - BSD-3-Clause
    - MIT
component  : office
summary    : Desktop publishing software
description: |
    Scribus is an Open Source program that brings professional page layout with a combination of press-ready output and new approaches to page design. Underneath a modern and user-friendly interface, Scribus supports professional publishing features, such as color separations, CMYK and spot colors, ICC color management, and versatile PDF creation.
patterns   :
    - docs :
        - /usr/share/doc
builddeps  :
    - pkgconfig(GraphicsMagick)
    - pkgconfig(hunspell)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(libpodofo)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler)
    - pkgconfig(python3)
    - pkgconfig(Qt5UiTools)
    - cups-devel
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/poppler-22.02.0.patch
    %patch -p1 < $pkgfiles/poppler-22.02.0-part2.patch
    %patch -p1 < $pkgfiles/poppler-22.03.0.patch
    %patch -p1 < $pkgfiles/poppler-22.04.0.patch
    %cmake_ninja -DWANT_NORPATH=1 -DWANT_GRAPHICSMAGICK=1 -DWANT_CPP17=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
