name       : scribus
version    : 1.5.6.1
release    : 25
source     :
    - https://sourceforge.net/projects/scribus/files/scribus-devel/1.5.6.1/scribus-1.5.6.1.tar.gz/download : 310f0d83200f1778d00ff7806e053ab01eaf5ec41ee78174e298c3ce24bdafaa
license    :
    - LGPL-2.0-or-later
    - BSD-3-Clause
    - MIT
component  : office
summary    : Desktop publishing software
description: |
    Scribus is an Open Source program that brings professional page layout with a combination of press-ready output and new approaches to page design. Underneath a modern and user-friendly interface, Scribus supports professional publishing features, such as color separations, CMYK and spot colors, ICC color management, and versatile PDF creation.
patterns   :
    - docs :
        - /usr/share/doc
builddeps  :
    - pkgconfig(GraphicsMagick)
    - pkgconfig(hunspell)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(libpodofo-0)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler)
    - pkgconfig(python3)
    - pkgconfig(Qt5UiTools)
    - cups-devel
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/poppler-21.3.0.patch
    %patch -p0 < $pkgfiles/poppler-21.4.0.patch
    %cmake_ninja -DWANT_NORPATH=1 -DWANT_GRAPHICSMAGICK=1
build      : |
    %ninja_build
install    : |
    %ninja_install
    # install -Dm00644 scribus.desktop $installdir/usr/share/applications/scribus.desktop

