name       : scribus
version    : 1.4.5
release    : 1
source     :
    - http://skylink.dl.sourceforge.net/project/scribus/scribus/1.4.5/scribus-1.4.5.tar.bz2 : 9f706f0561d26bb11bbe558690ae0507cd3689e381f6e17aa9411d9c4ef58498
license    : GPL-2.0
summary    : Desktop publishing software
description: |
    Desktop publishing software
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gl)
    - pkgconfig(lcms2)
    - pkgconfig(libtiff-4)
    - pkgconfig(python-2.7)
    - pkgconfig(QtCore)
    - cups-devel
    - ghostscript-devel
    - hyphen-devel
    - libboost-devel
    - libjpeg-turbo-devel
    - podofo-devel
setup      : |
    ln -s /usr/bin/rcc-qt4 /usr/bin/rcc
    %cmake .
build      : |
    %make
install    : |
    %make_install
    install -Dm644 scribus.desktop $installdir/usr/share/applications/scribus.desktop
    install -Dm644 resources/icons/AppIcon.png $installdir/usr/share/icons/hicolor/32x32/apps/scribus.png
