name       : scribus
version    : 1.4.8
release    : 13
source     :
    - https://datapacket.dl.sourceforge.net/project/scribus/scribus/1.4.8/scribus-1.4.8.tar.xz : 22253bb5994023f39608b37c57c7cd0280059fd97d2a4d71d4011aeeeb18042f
license    :
    - LGPL-2.0-or-later
    - BSD-3-Clause
    - MIT
component  : office
summary    : Desktop publishing software
description: |
    Scribus is an Open Source program that brings professional page layout with a combination of press-ready output and new approaches to page design. Underneath a modern and user-friendly interface, Scribus supports professional publishing features, such as color separations, CMYK and spot colors, ICC color management, and versatile PDF creation.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gl)
    - pkgconfig(lcms2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libpodofo-0)
    - pkgconfig(QtCore)
    - cups-devel
    - ghostscript-devel
    - hyphen-devel
    - libboost-devel
setup      : |
    %cmake -DQT_MOC_EXECUTABLE=/usr/bin/moc-qt4 \
           -DQT_RCC_EXECUTABLE=/usr/bin/rcc-qt4 \
           -DQT_UIC_EXECUTABLE=/usr/bin/uic-qt4 \
           .
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 scribus.desktop $installdir/usr/share/applications/scribus.desktop
    install -Dm00644 resources/icons/AppIcon.png $installdir/usr/share/icons/hicolor/32x32/apps/scribus.png

