name       : scribus
version    : 1.4.6
release    : 7
source     :
    - https://kent.dl.sourceforge.net/project/scribus/scribus/1.4.6/scribus-1.4.6.tar.xz : 21e336500d9edc9c90ccf73087e5ef3df59ec3e4a3cbfec15367bcd8d078a19a
license    : GPL-2.0
component  : office
summary    : Desktop publishing software
description: |
    Desktop publishing software
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gl)
    - pkgconfig(lcms2)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libpodofo-0)
    - pkgconfig(QtCore)
    - cups-devel
    - ghostscript-devel
    - hyphen-devel
    - libboost-devel
setup      : |
    %cmake -DQT_MOC_EXECUTABLE=/usr/bin/moc-qt4 \
           -DQT_RCC_EXECUTABLE=/usr/bin/rcc-qt4 \
           -DQT_UIC_EXECUTABLE=/usr/bin/uic-qt4 \
           .
build      : |
    %make
install    : |
    %make_install
    install -Dm644 scribus.desktop $installdir/usr/share/applications/scribus.desktop
    install -Dm644 resources/icons/AppIcon.png $installdir/usr/share/icons/hicolor/32x32/apps/scribus.png

