name       : scribus
version    : 1.5.5
release    : 16
source     :
    - https://sourceforge.net/projects/scribus/files/scribus-devel/1.5.5/scribus-1.5.5.tar.gz/download : 22fd7a149f360b91a613d3485da4bad7c065770d39b5570447985170e9c727eb
license    :
    - LGPL-2.0-or-later
    - BSD-3-Clause
    - MIT
component  : office
summary    : Desktop publishing software
description: |
    Scribus is an Open Source program that brings professional page layout with a combination of press-ready output and new approaches to page design. Underneath a modern and user-friendly interface, Scribus supports professional publishing features, such as color separations, CMYK and spot colors, ICC color management, and versatile PDF creation.
builddeps  :
    - pkgconfig(GraphicsMagick)
    - pkgconfig(hunspell)
    - pkgconfig(lcms2)
    - pkgconfig(libjpeg)
    - pkgconfig(libpodofo-0)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler)
    - pkgconfig(Qt5UiTools)
    - cups-devel
    - libboost-devel
setup      : |
    %apply_patches
    %cmake_ninja -DWANT_NORPATH=1 -DWANT_GRAPHICSMAGICK=1
build      : |
    %ninja_build
install    : |
    %ninja_install
    # install -Dm00644 scribus.desktop $installdir/usr/share/applications/scribus.desktop

